[package]
name = "metadata"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
directories = "6.0.0"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3.20.0"
filetime = "0.2"
