[package]
name = "planner"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
metadata = { path = "../metadata" }

thiserror.workspace = true
parking_lot.workspace = true
time.workspace = true

[dev-dependencies]
tempfile = "3.20.0"
